version: "3"
services:
  eventival-backend:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - REST_PORT=8080
      - STORAGE_BACKEND=mongo
      - MONGO_URI=mongodb://mongo:27017
  mongo:
    image: "mongo:4.2"