// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/user/interface/rpc/v1.0/protocol/user_service.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ff9881153db6f7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ListUserRequestType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequestType) Reset()         { *m = ListUserRequestType{} }
func (m *ListUserRequestType) String() string { return proto.CompactTextString(m) }
func (*ListUserRequestType) ProtoMessage()    {}
func (*ListUserRequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ff9881153db6f7, []int{1}
}

func (m *ListUserRequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequestType.Unmarshal(m, b)
}
func (m *ListUserRequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequestType.Marshal(b, m, deterministic)
}
func (m *ListUserRequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequestType.Merge(m, src)
}
func (m *ListUserRequestType) XXX_Size() int {
	return xxx_messageInfo_ListUserRequestType.Size(m)
}
func (m *ListUserRequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequestType.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequestType proto.InternalMessageInfo

type ListUserResponseType struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResponseType) Reset()         { *m = ListUserResponseType{} }
func (m *ListUserResponseType) String() string { return proto.CompactTextString(m) }
func (*ListUserResponseType) ProtoMessage()    {}
func (*ListUserResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ff9881153db6f7, []int{2}
}

func (m *ListUserResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponseType.Unmarshal(m, b)
}
func (m *ListUserResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponseType.Marshal(b, m, deterministic)
}
func (m *ListUserResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponseType.Merge(m, src)
}
func (m *ListUserResponseType) XXX_Size() int {
	return xxx_messageInfo_ListUserResponseType.Size(m)
}
func (m *ListUserResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponseType proto.InternalMessageInfo

func (m *ListUserResponseType) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type RegisterUserRequestType struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequestType) Reset()         { *m = RegisterUserRequestType{} }
func (m *RegisterUserRequestType) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequestType) ProtoMessage()    {}
func (*RegisterUserRequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ff9881153db6f7, []int{3}
}

func (m *RegisterUserRequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequestType.Unmarshal(m, b)
}
func (m *RegisterUserRequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequestType.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequestType.Merge(m, src)
}
func (m *RegisterUserRequestType) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequestType.Size(m)
}
func (m *RegisterUserRequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequestType.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequestType proto.InternalMessageInfo

func (m *RegisterUserRequestType) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterUserResponseType struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponseType) Reset()         { *m = RegisterUserResponseType{} }
func (m *RegisterUserResponseType) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponseType) ProtoMessage()    {}
func (*RegisterUserResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_13ff9881153db6f7, []int{4}
}

func (m *RegisterUserResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponseType.Unmarshal(m, b)
}
func (m *RegisterUserResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponseType.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponseType.Merge(m, src)
}
func (m *RegisterUserResponseType) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponseType.Size(m)
}
func (m *RegisterUserResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponseType proto.InternalMessageInfo

func (m *RegisterUserResponseType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*ListUserRequestType)(nil), "protocol.ListUserRequestType")
	proto.RegisterType((*ListUserResponseType)(nil), "protocol.ListUserResponseType")
	proto.RegisterType((*RegisterUserRequestType)(nil), "protocol.RegisterUserRequestType")
	proto.RegisterType((*RegisterUserResponseType)(nil), "protocol.RegisterUserResponseType")
}

func init() {
	proto.RegisterFile("pkg/user/interface/rpc/v1.0/protocol/user_service.proto", fileDescriptor_13ff9881153db6f7)
}

var fileDescriptor_13ff9881153db6f7 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x4f, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0xa3, 0x95, 0x3a, 0x95, 0x1e, 0xc6, 0x8a, 0xa1, 0xa0, 0xd4, 0xc5, 0x43, 0x11, 0xc9,
	0x6a, 0x3d, 0x78, 0xf1, 0x1f, 0xe8, 0x29, 0x2a, 0x1e, 0xa5, 0xa6, 0x63, 0x59, 0xac, 0xcd, 0xba,
	0xb3, 0x2d, 0xf8, 0xbb, 0xfc, 0x83, 0x92, 0x0d, 0x61, 0xd7, 0xd2, 0x1c, 0xe7, 0x7d, 0xcc, 0x7b,
	0x0f, 0xee, 0xcc, 0xe7, 0x5c, 0xad, 0x98, 0xac, 0xd2, 0x4b, 0x47, 0xf6, 0x63, 0x5a, 0x90, 0xb2,
	0xa6, 0x50, 0xeb, 0x9b, 0xec, 0x5a, 0x19, 0x5b, 0xba, 0xb2, 0x28, 0x17, 0x5e, 0xf0, 0xc6, 0x64,
	0xd7, 0xba, 0xa0, 0xcc, 0xa3, 0xd8, 0x6d, 0x48, 0x79, 0x05, 0x7b, 0x2f, 0x4c, 0x16, 0xfb, 0x90,
	0xe8, 0x59, 0x2a, 0x46, 0x62, 0x7c, 0x90, 0x27, 0x7a, 0x86, 0x03, 0xe8, 0xd0, 0xd7, 0x54, 0x2f,
	0xd2, 0xc4, 0x43, 0xf5, 0x21, 0x8f, 0xe1, 0xe8, 0x51, 0xb3, 0xab, 0x1c, 0x39, 0x7d, 0xaf, 0x88,
	0xdd, 0xf3, 0x8f, 0x21, 0x79, 0x0f, 0x83, 0x00, 0xb3, 0x29, 0x97, 0x4c, 0x15, 0x8e, 0x17, 0xd0,
	0xa9, 0xc2, 0x39, 0x15, 0xa3, 0xdd, 0x71, 0x6f, 0xd2, 0xcf, 0x9a, 0xd8, 0xcc, 0x4b, 0x6b, 0x52,
	0x2a, 0x38, 0xc9, 0x69, 0xae, 0xd9, 0x91, 0xdd, 0x78, 0x1c, 0x5a, 0x88, 0xb8, 0xc5, 0x25, 0xa4,
	0xff, 0x0d, 0x51, 0xe4, 0xc6, 0x8e, 0xc9, 0xaf, 0x80, 0x5e, 0x25, 0x7a, 0xaa, 0xf7, 0xe3, 0x03,
	0x74, 0x9b, 0xaa, 0x78, 0x1a, 0xfa, 0x6c, 0x59, 0x35, 0x3c, 0xdb, 0x46, 0x87, 0x28, 0xb9, 0x83,
	0xaf, 0x70, 0x18, 0x17, 0xc1, 0xf3, 0xe0, 0x68, 0x59, 0x34, 0x94, 0x6d, 0x92, 0xf8, 0xf1, 0xfb,
	0xbe, 0x17, 0xdd, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x62, 0xfc, 0x6b, 0xe1, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequestType, opts ...grpc.CallOption) (*RegisterUserResponseType, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error) {
	out := new(ListUserResponseType)
	err := c.cc.Invoke(ctx, "/protocol.UserService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequestType, opts ...grpc.CallOption) (*RegisterUserResponseType, error) {
	out := new(RegisterUserResponseType)
	err := c.cc.Invoke(ctx, "/protocol.UserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUser(context.Context, *ListUserRequestType) (*ListUserResponseType, error)
	RegisterUser(context.Context, *RegisterUserRequestType) (*RegisterUserResponseType, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/user/interface/rpc/v1.0/protocol/user_service.proto",
}
